FROM python:3.8-slim-buster
WORKDIR /frontendapp

COPY requirements.txt /frontendapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /frontendapp

EXPOSE 5000

# Start the Flask app
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]