FROM python:3.8-slim-buster
WORKDIR /orderapp

COPY requirements.txt /orderapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /orderapp

EXPOSE 5002

# Start the Flask app
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]