FROM python:3.8-slim-buster
WORKDIR /bookapp

COPY requirements.txt /bookapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /bookapp

EXPOSE 5001

# Start the Flask app
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]